### PR TITLE
ci: update CI process

### PR DESCRIPTION
**Pull request by andrewthetechie**
Apologies for the delay in getting this in, I got busy. This is the PR we discussed
over reddit.

This makes changes to CI and testing for this repo.

* Moves to using Nox to test on multiple python version (3.7, 3.8. 3.9. 3.10). This is configured via noxfile.py
* Adds pre-commit hooks (.pre-commit-config.yaml) to do linting and testing of code at commit time
* Uses pytest-cov to gather coverage info for the repo and upload it to codecov.io
* Adds flake8 linting
* Adds bandit security scanning
* Adds safety dependency scanning
* Adds dependabot dependency updates and alerts and a GHA workflow to automatically merge dependabot PRs that pass CI.
* Adds a GHA workflow to manage releases using release-please and conventional commits (release-please.yml)
* Adds a GHA workflow to upload releases to pypi automatically (release.yml)
* Adds a GHA workflow to manage repo settings (repo-manager.yml)
* Documents how to use some of these new features in CONTRIBUTING.rst and other docs.\

I know this is a ton of change, so I'm happy to discuss it/demo more or make changes as 
you'd like.

From your side, the only thing you'll have to do is setup the secrets mentioned in 
.github/README.md on the repo and all the CI should work as expected

The biggest changes for you in doing development would be:
* you need python 3.7, 3.8, 3.9, and 3.10 available for testing with nox. I suggest pyenv
* You can still run tests with pytest, but if you want to run the full test suite locally, you can run nox

After merging this PR, I'd suggest creating a new virtualenv using pyenv and setting up all the requirements from scratch

### CODE REVIEW

**Comment by andrewthetechie** [comment]
The result of the GHA runs can be seen in my fork here https://github.com/andrewthetechie/ducks/actions/runs/3116871819

**Comment by manimino** [comment]
This looks amazing! Thank you for tackling all this, it's a huge peace of mind to know ducks will actually work in the various python versions especially. And a clean CI is a wonderful thing. PyPI automation's fantastic too. Got the PyPI token in already, will add the GitHub one next.

The only part I'm wary on is the repo settings manager. It's a cool project, but I'm not sure it fits here. Changing repo settings is pretty powerful; if it ever went wrong, it could potentially break things in a way I wouldn't be able to fix. How do you feel about taking that out? I'm good with merging everything else.

**Comment by andrewthetechie** [comment]
You're welcome, glad to help.

I've pushed a commit removing repo-manager

**Comment by manimino** [comment]
All right, both tokens are in and the merge is complete. :tada:

**Pull request merged**
